"""Fix schema issues

Revision ID: 4fe09494574a
Revises: fbbd4667baf3
Create Date: 2025-04-04 11:20:00.288965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe09494574a'
down_revision: Union[str, None] = 'fbbd4667baf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ragdoc',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),  # Corrected here
    sa.Column('content', sa.String(), nullable=False),  # Corrected here
    sa.Column('category', sa.String(), nullable=False),  # Corrected here
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),  # Corrected here
    sa.Column('email', sa.String(), nullable=False),  # Corrected here
    sa.Column('hashed_password', sa.String(), nullable=False),  # Corrected here
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.String(), nullable=False),  # Corrected here
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.drop_table('user_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_new',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('created_on', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('message')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('ragdoc')
    # ### end Alembic commands ###